name: Deploy Simple Social App

on:
  push:
    branches:
      - main  # change to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js (use latest stable version)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies (skip if no package.json)
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json found, skipping npm install."
          fi

      # Step 4: Build (optional — skip if you don’t use React build)
      - name: Build project
        run: |
          if [ -f package.json ]; then
            npm run build
          else
            echo "No build step required."
          fi

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # since your files are directly in root
